version: "1.0"
info:
  model: int-scaffold
packages:
- name: Github_bearertoken_1212Project
  gitServerName: srcGithubCtrl_Arti_bearer
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
